name: Gerar PDF da Newsletter

on:
  workflow_dispatch:
    inputs:
      pasta:
        description: 'Nome da pasta da edição (ex: marco)'
        required: true
        default: 'marco'
      log_level:
        description: 'Log level'
        required: false
        default: 'info'
        type: choice
        options:
          - info
          - debug
          - error

jobs:
  gerar-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências
        run: |
          npm ci
          npm install puppeteer

      - name: Validar configurações
        run: node -e "
          const fs = require('fs');
          try {
            require('./conversor.js');
            console.log('✅ Configurações validadas');
          } catch (error) {
            console.error('❌ Erro ao carregar conversor.js:', error);
            process.exit(1);
          }
          "

      - name: Gerar PDF da edição
        run: |
          chmod +x gerar-pdf.sh
          ./gerar-pdf.sh ${{ github.event.inputs.pasta }}

      - name: Fazer upload do PDF como artefato
        uses: actions/upload-artifact@v4
        with:
          name: newsletter-${{ github.event.inputs.pasta }}
          path: newsletters/${{ github.event.inputs.pasta }}/output.pdf
          retention-days: 30